language: java

jdk:
  - openjdk8

services:
  - docker

addons:
  sonarcloud:
    organization: "openwms-github"

script:
  - sonar-scanner
  - mvn -Dmaven.test.error.ignore=true -Dmaven.test.failure.ignore=true clean package sonar:sonar -Psonar
  - mvn clean package

after_success:
  - docker build -t openwms/org.openwms.common.service:latest .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master