language: java

jdk:
  - openjdk8

services:
  - docker

addons:
  sonarcloud:
    organization: "openwms-github"

script:
  - sonar-scanner
  - mvn -Dmaven.test.error.ignore=true -Dmaven.test.failure.ignore=true clean package sonar:sonar -Psonar && exit 0
  - mvn site scm-publish:publish-scm -Denforcer.skip=true -Dscmpublish.pubScmUrl=scm:git:https://github.com/openwms/org.openwms.common.service.git && exit 0
  - mvn clean package -Denforcer.skip=true && exit 0

after_success:
  - docker build -t openwms/org.openwms.common.service:latest .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master