language: java

jdk:
  - openjdk8

cache:
  directories:
    - .autoconf
    - $HOME/.m2

services:
  - docker
  - rabbitmq

addons:
  sonarcloud:
    organization: "openwms-github"

script:
  - mvn clean package sonar:sonar -Dmaven.test.error.ignore=true -Dmaven.test.failure.ignore=true -Dci.buildNumber=$TRAVIS_BUILD_NUMBER -Psonar,ASYNCHRONOUS,TEST -U
  - mvn site scm-publish:publish-scm -Denforcer.skip=true -Dscmpublish.pubScmUrl=scm:git:https://${PUSHKEY}@github.com/openwms/org.openwms.common.service.git -DdeveloperConnectionUrl=scm:git:https://${PUSHKEY}@github.com/openwms/org.openwms.common.service.git -Dci.buildNumber=$TRAVIS_BUILD_NUMBER
  - mvn clean package -Denforcer.skip=true -Dci.buildNumber=$TRAVIS_BUILD_NUMBER -Prelease,gpg

after_success:
  - docker build -t openwms/org.openwms.common.service:latest .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master