language: java

jdk:
  - openjdk8

services:
  - docker

addons:
  sonarcloud:
    organization: "openwms-github"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Pit
  - sonar-scanner

after_success:
  - docker build -t openwms/org.openwms.common.service:latest .

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master