language: java

jdk:
  - openjdk8

cache:
  directories:
    - .autoconf
    - $TRAVIS_HOME/.m2

services:
  - docker
  - rabbitmq
  - postgresql

before_script:
  - psql -c 'create database TESTDB;' -U postgres

addons:
  sonarcloud:
    organization: "openwms-github"
  postgresql: "9.6"

script:
  - mvn clean package sonar:sonar -DsurefireArgs=-Dspring.profiles.active=ASYNCHRONOUS,TEST -Dmaven.test.error.ignore=true -Dmaven.test.failure.ignore=true -Dci.buildNumber=$TRAVIS_BUILD_NUMBER -Psonar -U -B
  - mvn site scm-publish:publish-scm -DsurefireArgs=-Dspring.profiles.active=ASYNCHRONOUS,TEST -Denforcer.skip=true -Dscmpublish.pubScmUrl=scm:git:https://${PUSHKEY}@github.com/openwms/org.openwms.common.service.git -DdeveloperConnectionUrl=scm:git:https://${PUSHKEY}@github.com/openwms/org.openwms.common.service.git -Dci.buildNumber=$TRAVIS_BUILD_NUMBER -B
  - mvn clean package -DsurefireArgs=-Dspring.profiles.active=ASYNCHRONOUS,TEST -Denforcer.skip=true -DskipTests=true -Dci.buildNumber=$TRAVIS_BUILD_NUMBER -Prelease,gpg -B
  - if [[ ("$TRAVIS_EVENT_TYPE" == "cron") ]]; then
    mvn clean install -DsurefireArgs=-Dspring.profiles.active=ASYNCHRONOUS,TEST,TESTPG -Denforcer.skip=true -DskipTests=true -Dci.buildNumber=$TRAVIS_BUILD_NUMBER -Prelease,gpg,schemagen -B;
    fi

after_success:
  - docker build -t openwms/org.openwms.common.service:latest .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
