language: java

jdk:
  - openjdk8

services:
- docker

before_install:
- docker build -t openwms/org.openwms.common.service .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master