apiVersion: apps/v1
kind: Deployment
metadata:
  name: owms-broker
  labels:
    app: owms-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: owms-broker
  template:
    metadata:
      labels:
        app: owms-broker
    spec:
      containers:
        - name: owms-broker
          image: rabbitmq:3-management
          imagePullPolicy: Always
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: hostname
              value: owms-broker
---
apiVersion: v1
kind: Service
metadata:
  name: owms-broker
spec:
  ports:
  - port: 5672
    protocol: TCP
    name: mgmt
    targetPort: 5672
  - port: 15672
    protocol: TCP
    name: ui
    targetPort: 15672
  selector:
    app: owms-broker
---
apiVersion: v1
kind: Service
metadata:
  name: owms-broker
  labels:
    app: owms-broker
spec:
  type: LoadBalancer
  ports:
    - port: 15672
      protocol: TCP
      targetPort: 15672
  selector:
    app: owms-broker
