eureka:
  client:
    healthcheck:
      enabled: true

---
spring:
  profiles: ASYNCHRONOUS
owms:
  commands:
    common:
      tu:
        exchange-name: common.tu.commands
        routing-key: tu.*
        queue-name: common-tu-commands-queue
  events:
    common:
      lg:
        exchange-name: common.lg
      tu:
        exchange-name: common.tu
        routing-key: tu.event.change.target