eureka:
  client:
    healthcheck:
      enabled: true

---
spring:
  profiles: ASYNCHRONOUS
owms:
  commands:
    common:
      tu:
        exchange-name: common.tu.commands
        routing-key: tu.*
  events:
    common:
      lg:
        exchange-name: common.lg
        routing-key: lg.event.*
      tu:
        exchange-name: common.tu
        routing-key: tu.event.change.target