eureka:
  client:
    healthcheck:
      enabled: true

---
spring:
  profiles: ASYNCHRONOUS

owms:
  commands:
    common:
      tu:
        exchange-name: common.tu.commands
        routing-key: common.tu.command.*
        queue-name: common-tu-commands-queue
  events:
    common:
      lg:
        exchange-name: common.lg
        routing-key: lg.event.*
        queue-name: common-lg-queue
      loc:
        exchange-name: common.loc
        routing-key: loc.event.*
      tu:
        exchange-name: common.tu
        routing-key: tu.event.change.target
        queue-name: common-service