spring:
  main:
    banner-mode: "off"

management:
  port: 8990

logging:
  level:
    root: INFO
    com.netflix.discovery: 'OFF'

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

info:
  component: Turbine

spring:
  oauth2:
    resource:
      userInfoUri: https://api.github.com/user
      preferTokenInfo: false