eureka:
  client:
    healthcheck:
      enabled: true

---
spring:
  profiles: ASYNCHRONOUS

owms:
  common:
    dead-letter:
      exchange-name: dle.common
      queue-name: common-dl-queue
  commands:
    common:
      loc:
        exchange-name: common.loc.commands
        routing-key: common.loc.command.in.*
        queue-name: common-loc-commands-queue
      tu:
        exchange-name: common.tu.commands
        routing-key: common.tu.command.in.*
        queue-name: common-tu-commands-queue
      tx:
        exchange-name: common.tx.commands
  events:
    common:
      lg:
        exchange-name: common.lg
      tu:
        exchange-name: common.tu
      tut:
        exchange-name: common.tu
