eureka:
  client:
    healthcheck:
      enabled: true

---
spring:
  profiles: ASYNCHRONOUS
owms:
  events:
    common:
      lg:
        exchange-name: common.lg
      tu:
        exchange-name: common.tu
        change-target: tu.event.change.target