spring:
  main:
    banner-mode: "off"

management:
  port: 8990

logging:
  level:
    root: INFO
    com.netflix.discovery: 'OFF'

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

