on: [push]

env:
  MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
  PUSHKEY: ${{ secrets.PUSHKEY }}

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Build & Test Microservice
    services:
      postgres:
        image: openwms/postgres-image:latest
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Install tools
        run: sudo apt-get install graphviz
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build
        run: >
          ./mvnw clean package
          -DsurefireArgs=-Dspring.profiles.active=TEST
          -Dci.buildNumber=$GITHUB_RUN_NUMBER
          -U -B $MAVEN_OPTS
      - name: Site
        run: >
          ./mvnw site scm-publish:publish-scm
          -DM2_REPO_DIR=/home/runner/.m2/repository
          -DsurefireArgs=-Dspring.profiles.active=ASYNCHRONOUS,TEST,TESTPG
          -Dargs=-Dspring.profiles.active=ASYNCHRONOUS,TEST,TESTPG
          -Dspring.datasource.url=jdbc://postgres:5432/testdb
          -DDB_HOST=localhost
          -DDB_USERNAME=KARL
          -DDB_PASSWORD=KARL
          -Dscmuser=$PUSHKEY
          -Dscmpublish.pubScmUrl=scm:git:https://$PUSHKEY@github.com/openwms/org.openwms.common.service.git
          -DdeveloperConnectionUrl=scm:git:https://$PUSHKEY@github.com/openwms/org.openwms.common.service.git
          -Dci.buildNumber=$GITHUB_RUN_NUMBER
          -Pschemagen -B $MAVEN_OPTS
