on: [push]

env:
  MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
  PUSHKEY: ${{ secrets.PUSHKEY }}

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    container: node:10.18-jessie
    name: A job to say hello
    services:
      postgres:
        image: openwms/postgres-image:latest
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build
        run: >
          ./mvnw site scm-publish:publish-scm
          -DM2_REPO_DIR=/root/.m2/repository
          -Dspring.datasource.url=jdbc:postgresql://postgres/testdb
          -Dspring.datasource.username=KARL
          -Dspring.datasource.password=KARL
          -Dspring.rabbitmq.host=rabbitmq
          -DDB_HOST=postgres
          -DDB_USERNAME=KARL
          -DDB_PASSWORD=KARL
          -Denforcer.skip=true
          -Dscmuser=$PUSHKEY
          -Dscmpublish.pubScmUrl=scm:git:https://$PUSHKEY@github.com/openwms/org.openwms.common.service.git
          -DdeveloperConnectionUrl=scm:git:https://$PUSHKEY@github.com/openwms/org.openwms.common.service.git
          -Dci.buildNumber=$GITHUB_RUN_NUMBER
          -Pschemagen -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

      #      - name: Hello world action step
#        uses: ./.github/actions # Uses an action in the root directory
#        id: hello
      # Use the output from the `hello` step
